### PBS script to run a parallel matlab job 
### on the cluster

#PBS -l nodes=1:ppn=8,walltime=5:00:00
#PBS -N RobustLearning
#PBS -M apb296@nyu.edu
#PBS -m abe
#PBS -e localhost:/home/apb296/robust-learning-insurance/Errors.err
#PBS -o localhost:/home/apb296/robust-learning-insurance/Output.out 
source /etc/profile.d/env-modules.sh
module load matlab/R2011a
module load nag
module load git

cd /home/apb296/robust-learning-insurance/Matlab/InfiniteHorizon/Learning
/share/apps/matlab/R2011a/bin/matlab -nosplash < ComputeCoeffForAllCases.m -logfile /home/apb296/robust-learning-insurance/logMakePol.log

git add Data/Sim*.mat
git add Data/Final*.mat
git commit -m "Simulation Data from long run"
git push origin master

exit 0;


