### PBS script to run a parallel matlab job 
### on the cluster


#PBS -N RobustLearning
#PBS -M apb296@nyu.edu
#PBS -m abe
#PBS -e localhost:/home/apb296/robust-learning-insurance/Errors.err
#PBS -o localhost:/home/apb296/robust-learning-insurance/Output.out 
source /etc/profile.d/env-modules.sh
module load matlab/R2011a
module load nag

cd /home/apb296/robust-learning-insurance/Matlab/InfiniteHorizon/Learning
/share/apps/matlab/R2011a/bin/matlab -nosplash < ComputeCoeffForAllCases.m -logfile /home/apb296/robust-learning-insurance/logMakePol.log

### You can add more stuff for the script to do after the job is completed

### E.g. zip up the ResultsDir for easy transfer
zip -r Results.zip ResultsDir/*.*

exit 0;


